### ISSUE TITLE
Signal: IRCVERS greater or equal to 5 should share join User-Mode as signal

### ISSUE THREAD

**Issue by jyonxo** [MSNLD/msnld-mirc#4]
This needs to be done during PARSELINE event. When a user joins a channel the decoration should be forwarded as a signal and stripped out of the message before forwarding to internal logic through parseline

Example of raw message with decoration:

<- :Nickname!xxxxx@GateKeeperPassport JOIN H,U,RX,. :%#Channel

The above should be shared via signal for theme processing

**Comment by realJoshByrnes** [comment]
Formats:

IRC7
`<Status>,<User Level>,<Profile Type>`

IRC8
`<Status>,<User Level>,<Profile Type><Subscriber Info>`

A (Status)
- H (here)
- G (gone)

U (User Level)
- U (User)
- G (Guide)
- S (Sysop)
- A (Admin)

P (Profile Type)
- G (No Profile Information)
- RX - No Profile
- PX - Has Profile
- MX - Male, Has Profile
- FX - Female, Has Profile
- PY - Has Profile with Picture
- MY - Male, Has Profile with Picture
- FY - Female, Has Profile with Picture

S = Subscriber Info
- B (Subscriber)
- O (Non Subscriber)
